<a href="https://colab.research.google.com/github/vh8432348-ship-it/ITStep-AI/blob/main/%D0%9F%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Імпорт модуля pandas

In [7]:
import pandas as pd

Дані про пасажирів корабля:
* pclass -- клас білета(перший, другий або третій)
* sex -- стать
* age -- вік
* sibsp -- кількість братів\сестер та чоловіків\дружин на борту
* parch -- кількість дітей та батьків на борту
* fare -- вартість поїздки
* embarked -- Порт посадки (C = Шербур, Q = Квінстаун, S = Саутгемптон)

In [10]:
df = pd.read_csv("https://raw.githubusercontent.com/HalyshAnton/IT-Step-Pyton-AI/main/module2/data/ship_passengers.csv",
                 index_col="Unnamed: 0")

# Завдання 1

Вивести загальну інформацію про таблицю: кількість рядків та стовпців, назви стовпців та їхній тип даних, в яких стовпцях є пропущені значення

In [12]:
df.shape

(891, 7)

# Завдання 2
Скільки пасажирів сіло у Квінстауні?

In [14]:

mask = df["embarked"] == "Q"
df[mask].shape[0]

77

In [15]:
(df["embarked"] == "Q").sum()

np.int64(77)

# Завдання 3
Виведіть стать, вік та вартість поїздки для пасажирів з білетом першого класу

In [17]:
mask = df["pclass"] == 1
df[mask][["sex", "age", "fare"]]

        sex   age     fare
1    female  38.0  71.2833
3    female  35.0  53.1000
6      male  54.0  51.8625
11   female  58.0  26.5500
23     male  28.0  35.5000
..      ...   ...      ...
871  female  47.0  52.5542
872    male  33.0   5.0000
879  female  56.0  83.1583
887  female  19.0  30.0000
889    male  26.0  30.0000

[216 rows x 3 columns]

# Завдання 4
Ввиведіть дані про неповнолітніх чоловіків з Шербура

In [18]:
mask = (df["sex"] == "male") & (df["age"] < 18) & (df["embarked"] == "C")

df[mask]

     pclass   sex    age  sibsp  parch      fare embarked
125       3  male  12.00      1      0   11.2417        C
352       3  male  15.00      1      1    7.2292        C
532       3  male  17.00      1      1    7.2292        C
550       1  male  17.00      0      2  110.8833        C
731       3  male  11.00      0      0   18.7875        C
803       3  male   0.42      0      1    8.5167        C
827       2  male   1.00      0      2   37.0042        C

# Завдання 5
Створіть новий стовпчик relatives -- загальна кількість родичів на борту для кожного пасажира

In [19]:
df["relatives"] = df["sibsp"] + df["parch"]

# Завдання 6
Видаліть стовпчик, в якому найбільше пропусків. Якщо пропущені значення ще залишаться, видаліть рядки з пропусками

   pclass     sex   age  sibsp  parch     fare embarked  relatives
0       3    male  22.0      1      0   7.2500        S          1
1       1  female  38.0      1      0  71.2833        C          1
2       3  female  26.0      0      0   7.9250        S          0
3       1  female  35.0      1      0  53.1000        S          1
4       3    male  35.0      0      0   8.0500        S          0